Repository elastic/assetbeat, pull requests merged in 2023-10, with the labels that each got.

#351 Populate cloud.instance.id in azure nodes
  input/k8s/nodes.go
  input/k8s/util.go
  input/k8s/util_test.go
Labels: backport-skip

#352 Update README
  README.md
Labels: backport-skip

#346 [CI] Add explicit depends_on statements for packaging steps
  .buildkite/pipeline.yml
Labels: ci, backport-skip

#350 Add collector for VM scale sets instances
  input/azure/azure.go
  input/azure/vm.go
  input/azure/vm_test.go
Labels: backport-skip

#356 Bump version to 8.12
  version/version.go
Labels: backport-skip

#357 backport: Add 8.11 branch
  .mergify.yml
Labels: ci, release, backport-skip

#372 Add base folder to tar artifacts
  internal/dev-tools/package.go
  internal/dev-tools/tar.go
Labels: epic:elastic-agent, backport-v8.11.0

#384 Explicitly disable CGO
  internal/dev-tools/build.go
Labels: backport-v8.11.0
