Repository elastic/assetbeat, pull requests merged in 2023-09, with the labels that each got.

#308 Use `assets-raw-default` as default index for all inputs
  input/README.md
  input/aws/asset_test.go
  input/aws/aws.go
  input/aws/ec2.go
  input/aws/ec2_test.go
  input/aws/eks.go
  input/aws/vpc.go
  input/aws/vpc_test.go
  input/gcp/asset_test.go
  input/gcp/compute.go
  input/gcp/compute_test.go
  input/gcp/gke.go
  input/gcp/gke_test.go
  input/gcp/vpc.go
  input/gcp/vpc_test.go
  input/hostdata/hostdata.go
  input/hostdata/hostdata_test.go
  input/internal/config.go
  input/internal/ecs_test.go
  input/internal/index.go
  input/internal/index_test.go
  input/internal/publish.go
  input/internal/publish_test.go
  input/k8s/containers.go
  input/k8s/containers_test.go
  input/k8s/k8s.go
  input/k8s/k8s_test.go
  input/k8s/nodes.go
  input/k8s/nodes_test.go
  input/k8s/pods.go
  input/k8s/pods_test.go
Labels: enhancement

#323 Use x86_64 suffix in artifact names instead of amd64
  internal/dev-tools/package.go
  magefile.go
Labels: epic:elastic-agent

#314 Azure input with basic collector for VM instances
  NOTICE.txt
  go.mod
  go.sum
  input/azure/README.md
  input/azure/azure.go
  input/azure/azure_test.go
  input/azure/vm.go
  input/azure/vm_test.go
  input/default-inputs/inputs.go
Labels: enhancement, azure

#302 Add publish step in Buildkite, enable staging builds and add support for the version qualifier feature
  .buildkite/pipeline.yml
  .buildkite/scripts/publish.sh
  cmd/root.go
  internal/dev-tools/build.go
  internal/dev-tools/notice.go
  internal/dev-tools/package.go
  version/helper.go
  version/version.go
Labels: enhancement, epic:elastic-agent

#325 Enable DRA publishing
  .buildkite/scripts/publish.sh
Labels: epic:elastic-agent

#326 Fix dra script permissions
  .buildkite/scripts/publish.sh
Labels: epic:elastic-agent

#331 Add Elastic Agent spec file
  assetbeat.spec.yml
  internal/dev-tools/package.go
  internal/dev-tools/tar.go
Labels: epic:elastic-agent

#334 Add asset.metadata.state field to kubernetes node assets
  input/k8s/k8s_test.go
  input/k8s/nodes.go
  input/k8s/util.go
Labels: enhancement, k8s

#338 Add `.go-version` file
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .github/workflows/post-dependabot.yml
  .go-version
Labels: ci

#340 ci(Mergify): configuration update
  .mergify.yml
Labels: ci

#342 Add `asset.name` for AWS assets
  input/aws/README.md
  input/aws/ec2.go
  input/aws/ec2_test.go
  input/aws/eks.go
  input/aws/vpc.go
  input/aws/vpc_test.go
Labels: aws, backport-skip

#344 Add `asset.name` for Azure assets
  input/azure/README.md
  input/azure/vm.go
  input/azure/vm_test.go
Labels: azure, backport-skip
